compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

enableImmutableInstalls: false

# Disable production flag that causes issues with Yarn v4
enableProductionMode: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
